article/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'
urlpatterns = [
    # 文章列表页视图
    path('', views.ArticleListView.as_view(), name='index'),
    path('list/', views.ArticleListView.as_view(), name='list'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
]

i4net/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # 文章
    path('', views.ArticleListView.as_view(), name='index'),
    path('article/', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# 状态选项
from django.utils.safestring import mark_safe

STATUS_CHOICES = ((1, '启用'), (2, '禁用'),)


class ArticleColumn(models.Model):
    title = models.CharField('栏目标题', max_length=100)
    enabled = models.PositiveSmallIntegerField('启用状态', choices=STATUS_CHOICES, default=STATUS_CHOICES[0])
    created = models.DateTimeField('创建时间', auto_now_add=True)
    updated = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        db_table = 'article_column'
        verbose_name = '文章栏目'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def get_article_list(self):
        article_list = self.articlepost_set.filter(enabled=1)
        return article_list


class ArticlePost(models.Model):
    column = models.ForeignKey(ArticleColumn, verbose_name='文章栏目', on_delete=models.CASCADE)
    title = models.CharField('文章标题', max_length=100)
    digest = models.TextField('摘要', max_length=255)
    content = RichTextField(verbose_name='文章内容')
    page_view = models.PositiveIntegerField(verbose_name='浏览量', default=0)
    enabled = models.PositiveSmallIntegerField('启用状态', choices=STATUS_CHOICES, default=STATUS_CHOICES[0])
    created = models.DateTimeField('创建时间', auto_now_add=True)
    updated = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        db_table = 'article_post'
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def get_full_title(self):
        return f"{self.column.title} - {self.title}"

article/views.py
from django.views import generic

from .models import ArticlePost, ArticleColumn


class ArticleContextMixin:
    article_columns = ArticleColumn.objects.filter(enabled=1)
    extra_context = {'article_columns': article_columns}


# 文章列表
class ArticleListView(ArticleContextMixin, generic.ListView):
    template_name = 'article/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        qs = ArticlePost.objects.filter(enabled=1, column__enabled=1)
        return qs


# 文章详情
class ArticleDetailView(generic.DetailView):
    template_name = 'article/detail.html'
    model = ArticlePost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        column = self.get_object().column
        context['article_list'] = ArticlePost.objects.filter(column=column, enabled=1)
        return context

article/templates/article/detail.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="container bg-white p-4" style="border-radius: 5px;">
        <h1>{{ articlepost.get_full_title }}</h1>
        <div class="fs-12">
            <a href="#">
                <i class="my-fa fa fa-book" aria-hidden="true"></i>&nbsp;《{{ articlepost.column }}》
            </a>
            <a href="#">
                <i class="my-fa fa fa-calendar ml-2" aria-hidden="true"></i>&nbsp;{{ articlepost.updated|date }}
            </a>
        </div>
        <hr/>
        {{ articlepost.content|safe }}
    </div>
{% endblock %}

{% block content_right %}
    <div class="card mb-3">
        <div class="card-header p-2 fs-14">
            文章目录
        </div>
        <div class="card-body p-1 fs-13">
            <ul class="list-group list-group-flush">
                {% for item in article_list %}
                    <li class="list-group-item {% if item == object %}disabled{% endif %}">
                        <a href="{% url 'article:detail' item.id %}">
                            {{ item.get_full_title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

article/templates/article/index.html
{% extends 'base.html' %}

{% block main_content %}
    {{ title }}
    <!-- 面包屑 -->
    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item fs-15">
            <a class="breadcrumb-link active" href="#"><i class="my-fa fa fa-clock-o" aria-hidden="true"></i>&nbsp;时间排序</a>
        </li>
        <li class="breadcrumb-item fs-15">
            <a class="breadcrumb-link" href="#"><i class="my-fa fa fa-fire" aria-hidden="true"></i>&nbsp;热度排序</a>
        </li>
    </ol>
    <!--普通文章显示-->
    {% for article in article_list %}
        <div class="my-card card mb-3">
            <div class="card-body">
                <!-- 文章标题 -->
                <h1 class="mt-0 fs-15">
                    <a href="{% url 'article:detail' article.id %}" target="_blank">
                        <b>{{ article.get_full_title }}</b>
                    </a>
                </h1>
                <!-- 文章摘要 -->
                <span class="fs-13">{{ article.digest }}</span>
            </div>
            <div class="card-footer text-muted">
                <div class="fs-12">
                    <span><i class="my-fa fa fa-book" aria-hidden="true"></i>&nbsp;《{{ article.column }}》</span>
                    <span>
                            <i class="my-fa fa fa-calendar ml-2" aria-hidden="true"></i>&nbsp;{{ article.updated|date }}
                        </span>
                    <a class="float-right d-none d-lg-block" href="{% url 'article:detail' article.id %}"
                       target="_blank">
                        <b class="text-danger">开始阅读→</b>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/__navbar.html
<!--导航-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand p-0 ml-2 mr-2" href="/">
        <strong><span class="text-danger">个人</span>&nbsp;<span class="text-success">数据分享</span></strong>
    </a>
    {#    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"#}
    {#            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
    {#        <span class="navbar-toggler-icon"></span>#}
    {#    </button>#}

    {#    <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
    {#        <ul class="navbar-nav mr-auto fs-16">#}
    {#            <li class="nav-item active">#}
    {#                <a class="nav-link" href="/">文章</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="/">教程</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="/">知识</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="/">关于</a>#}
    {#            </li>#}
    {#        </ul>#}
    {#    </div>#}
</nav>

templates/__right_content.html
<div>
    <div class="card mb-3">
        <div class="card-header p-2 fs-14">
            每日一句
        </div>
        <div class="card-body p-2 fs-13">
            赠人玫瑰，手留余香。不忘初心，砥砺前行。
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header p-2 fs-14">
            文章分类
        </div>
        <div class="card-body p-1 fs-13">
            <ul class="list-group list-group-flush">
                {% for item in article_columns %}
                    <li class="list-group-item">
                        <a href="{% url 'article:index' %}" data-toggle="tooltip" data-placement="bottom" title=""
                           target="_blank" data-original-title="{{ item.title }}">
                            {{ item.title }}
                            <span class="badge badge-warning float-right mt-1">{{ item.get_article_list.count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 网站关键词 -->
    <meta name="keywords" content="Django, Python爬虫, Python学习, Web开发">
    <!-- 网站描述 -->
    <meta name="description" content="个人技术分享，主要为Python，Django，网络爬虫等。后期可能会扩展其他纬度">
    <!-- 网站图标 -->
    <link href="{% static 'blog/pic/icon.png' %}" rel="shortcut icon">
    <!-- 网站元 -->
    <title>个人数据分享{% if subtitle %}&nbsp;|&nbsp;{{ subtitle }}{% endif %}</title>
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/4.3.1/css/bootstrap.css' %}" rel="stylesheet">
    <!-- font awesome -->
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.css' %}">
    <!-- Global Style -->
    <link href="{% static 'blog/css/global.css' %}" rel="stylesheet">
</head>
<body style="background-color: WhiteSmoke;">
<!--导航-->
{% block navbar %}
    {% include '__navbar.html' %}
{% endblock %}
<!-- 提示信息 -->
{% block messages %}
    {% if not messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable text-center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

<!--主体内容-->
{% block wrapper %}
    <div class="container mt-3" style="height: auto !important;">
        <div class="row" style="height: auto !important;">
            <!-- Left -->
            <div class="col-lg-9">
                {% block main_content %}
                {% endblock %}
            </div>
            <!-- Right -->
            <div class="col-lg-3 d-none d-lg-block">
                {% block content_right %}
                    {% include '__right_content.html' %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

<!-- 底部备案号 -->
<footer class="bg-light mt-4 pt-3 pb-2 f-16">
    <div class="text-center">
        <p class="text-danger">皖ICP备19017840号-2</p>
        <p class="text-info">
            <strong><i>Copyright © 2019<a class="text-info" href="/"> i4NET</a> All rights reserved.</i></strong>
        </p>
    </div>
</footer>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'jquery/3.4.1/jquery.js' %}"></script>
<script src="{% static 'popper/1.15.0/popper.js' %}"></script>
<script src="{% static 'bootstrap/4.3.1/js/bootstrap.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>